"""add extra json to audit_findings

Revision ID: 81f38d205c5b
Revises: 
Create Date: 2026-01-26 22:01:08.870206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f38d205c5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('connection_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_id'), 'ai_models', ['id'], unique=False)
    op.create_index(op.f('ix_ai_models_model_id'), 'ai_models', ['model_id'], unique=True)
    op.create_table('audit_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('audit_frequency', sa.String(), nullable=True),
    sa.Column('baseline_strategy', sa.String(), nullable=True),
    sa.Column('audit_scope', sa.JSON(), nullable=True),
    sa.Column('policy_reference', sa.JSON(), nullable=True),
    sa.Column('active_audit_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_policies_id'), 'audit_policies', ['id'], unique=False)
    op.create_table('audit_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('audit_type', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('audit_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_audit_id'), 'audit_runs', ['audit_id'], unique=True)
    op.create_index(op.f('ix_audit_runs_id'), 'audit_runs', ['id'], unique=False)
    op.create_table('evidence_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=True),
    sa.Column('last_data_snapshot', sa.JSON(), nullable=True),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_sources_id'), 'evidence_sources', ['id'], unique=False)
    op.create_table('prompt_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('expected_behavior', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_interactions_audit_id'), 'audit_interactions', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_interactions_id'), 'audit_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_audit_interactions_prompt_id'), 'audit_interactions', ['prompt_id'], unique=False)
    op.create_table('audit_metric_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('likelihood', sa.Float(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('regulatory_weight', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('severity_score_100', sa.Float(), nullable=False),
    sa.Column('severity_band', sa.String(), nullable=False),
    sa.Column('strategic_weight', sa.Float(), nullable=False),
    sa.Column('framework_breakdown', sa.JSON(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_metric_scores_audit_id'), 'audit_metric_scores', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_metric_scores_id'), 'audit_metric_scores', ['id'], unique=False)
    op.create_index(op.f('ix_audit_metric_scores_metric_name'), 'audit_metric_scores', ['metric_name'], unique=False)
    op.create_table('audit_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=True),
    sa.Column('bias_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('critical_findings', sa.Integer(), nullable=True),
    sa.Column('high_findings', sa.Integer(), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_summaries_id'), 'audit_summaries', ['id'], unique=False)
    op.create_table('audit_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('deviation_percentage', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_runs.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['audit_interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_finding_id'), 'audit_findings', ['finding_id'], unique=True)
    op.create_index(op.f('ix_audit_findings_id'), 'audit_findings', ['id'], unique=False)
    op.create_index(op.f('ix_audit_findings_interaction_id'), 'audit_findings', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_prompt_id'), 'audit_findings', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_findings_prompt_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_interaction_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_finding_id'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index(op.f('ix_audit_summaries_id'), table_name='audit_summaries')
    op.drop_table('audit_summaries')
    op.drop_index(op.f('ix_audit_metric_scores_metric_name'), table_name='audit_metric_scores')
    op.drop_index(op.f('ix_audit_metric_scores_id'), table_name='audit_metric_scores')
    op.drop_index(op.f('ix_audit_metric_scores_audit_id'), table_name='audit_metric_scores')
    op.drop_table('audit_metric_scores')
    op.drop_index(op.f('ix_audit_interactions_prompt_id'), table_name='audit_interactions')
    op.drop_index(op.f('ix_audit_interactions_id'), table_name='audit_interactions')
    op.drop_index(op.f('ix_audit_interactions_audit_id'), table_name='audit_interactions')
    op.drop_table('audit_interactions')
    op.drop_table('prompt_tests')
    op.drop_index(op.f('ix_evidence_sources_id'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_index(op.f('ix_audit_runs_id'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_audit_id'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_audit_policies_id'), table_name='audit_policies')
    op.drop_table('audit_policies')
    op.drop_index(op.f('ix_ai_models_model_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_id'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
